# Generated by Django 4.2.7 on 2023-11-02 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField()),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'ACTIVA'), ('O', 'OCUPADA'), ('R', 'RECHAZADA')], default='P', max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_residencia', models.CharField(choices=[('A', 'APARTAMENTO'), ('C', 'CASA'), ('H', 'HABITACION')], max_length=1)),
                ('canon_cop', models.IntegerField()),
                ('area_m2', models.IntegerField()),
                ('habitaciones', models.IntegerField(default=1)),
                ('piso', models.IntegerField(default=1)),
                ('comuna', models.CharField(choices=[('1', 'POPULAR'), ('2', 'SANTA CRUZ'), ('3', 'MANRIQUE'), ('4', 'ARANJUEZ'), ('5', 'CASTILLA'), ('6', 'DOCE DE OCTUBRE'), ('7', 'ROBLEDO'), ('8', 'VILLA HERMOSA'), ('9', 'BUENOS AIRES'), ('10', 'LA CANDELARIA'), ('11', 'LAURELES ESTADIO'), ('12', 'LA AMERICA'), ('13', 'SAN JAVIER'), ('14', 'EL POBLADO'), ('15', 'GUAYABAL'), ('16', 'BELEN')], max_length=2)),
                ('estado_cambiado', models.BooleanField(default=True)),
                ('inquilino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencia', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'APROBADA'), ('C', 'CANCELADA'), ('R', 'RECHAZADA')], default='P', max_length=1)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado_cambiado', models.BooleanField(default=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='arriendos.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='arriendos.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='arriendos.publicacion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['P', 'A', 'C', 'R'])), name='valid_estado_solicitud'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(check=models.Q(('calificacion__gte', 1), ('calificacion__lte', 10)), name='valid_calificacion'),
        ),
        migrations.AddConstraint(
            model_name='publicacion',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['P', 'A', 'O', 'R'])), name='valid_estado_publicacion'),
        ),
        migrations.AddConstraint(
            model_name='publicacion',
            constraint=models.CheckConstraint(check=models.Q(('tipo_residencia__in', ['A', 'C', 'H'])), name='valid_tipo_residencia'),
        ),
    ]
