# Generated by Django 4.2.7 on 2023-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicacion',
            name='valid_tipo_residencia',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='tipo_residencia',
        ),
        migrations.AddConstraint(
            model_name='publicacion',
            constraint=models.CheckConstraint(check=models.Q(('comuna__in', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])), name='valid_comuna'),
        ),
    ]
