# Generated by Django 4.2.7 on 2023-11-02 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usuario_id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=2, null=True)),
                ('documento', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(db_column='contrasena')),
                ('celular', models.CharField()),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('rol', models.IntegerField(blank=True, choices=[(1, 'ARRENDADOR'), (2, 'ESTUDIANTE')], null=True)),
                ('validado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('tipo_documento__in', ['CC', 'CE', 'TI', 'PP'])), name='valid_tipo_documento'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('rol__in', [1, 2])), name='valid_rol'),
        ),
    ]
