# Generated by Django 4.2.7 on 2023-11-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
